stages:
  - build
  - deploy


bck_build:
    stage: build
    image:  maven:3.8.6-openjdk-18
    script:
      - cd BackEnd
      - echo "Building app..."
      - mvn clean install
      - echo "Finished building the app."
    artifacts:
      expire_in: 1 week
      paths:
          - BackEnd/target/gestionreservasapp.jar
    only:
       - CI/Execution

bck_deploy:
    stage: deploy
    needs: [bck_build]
    image: alpine:3.11
    before_script:
        - apk update && apk add openssh-client bash
        - mkdir -p ~/.ssh
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - touch ~/.ssh/config
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - ssh-keyscan -H "$DEPLOY_SERVER_IP" >> ~/.ssh/known_hosts
    script:
        - echo "Deploying started..."
        - echo "Directory in " $DEPLOY_SERVER_IP
        - ssh ubuntu@$DEPLOY_SERVER_IP "pwd"
        - ssh ubuntu@$DEPLOY_SERVER_IP "ls -ld *"
        - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl stop gestionreservasapp.service"
        - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl status gestionreservasapp.service"
        - scp BackEnd/target/gestionreservasapp.jar ubuntu@$DEPLOY_SERVER_IP:./gestion-reservas
        - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl daemon-reload"
        - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl start gestionreservasapp.service"
        - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl status gestionreservasapp.service"
        - echo "Finished deploying the app."
    only:
        - CI/Execution



fe_build:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "List project"
    - ls
    - cd Frontend
    - echo "List project frontend"
    - ls
  only:
    - frontend
