stages:
  - build

bck_build:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "List project"
    - ls
    - cd BackEnd
    - echo "List project backend"
    - ls
  only:
    - backend

fe_build:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "List project"
    - ls
    - cd Frontend
    - echo "List project frontend"
    - ls
  only:
    - frontend
