image:  maven:3.0.2-jdk-17

variables:
  EB_APP_JAR_NAME: "gestionreservasapp.jar"
  EB_APP_SERVICE_NAME: "gestionreservasapp.service"
  EB_APP_FILEDSERVICE_NAME: "gestion-reservas"


stages:
  - test
  - build
  - deploy

application_test:
  stage: test
  script:
    - mvn clean test -B
  only:
    - backend

application_build:
  stage: build
  script:
    - echo "Building app..."
    - mvn package -B -Dmaven.test.skip
    - echo "Finished building the app."
  artifacts:
    paths:
      - target/$EB_APP_JAR_NAME
  only:
    - backend

application_deploy:
  stage: deploy
  image: alpine:3.11
  before_script:
      - apk update && apk add openssh-client bash
      - mkdir -p ~/.ssh
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
      - touch ~/.ssh/config
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
  script:
      - echo "Deploying started..."
      - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl stop  $EB_APP_SERVICE_NAME"
      - scp ./target/$EB_APP_JAR_NAME ubuntu@$DEPLOY_SERVER_IP:~/$EB_APP_FILEDSERVICE_NAME
      - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl start $EB_APP_SERVICE_NAME"
      - echo "Finished deploying the app."
  only:
      - backend
